# Generated by Django 2.1.2 on 2018-10-19 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids', models.FloatField()),
                ('temperature', models.FloatField()),
                ('tension', models.FloatField()),
                ('motifs', models.CharField(max_length=500)),
                ('examenClinique', models.CharField(max_length=500)),
                ('diagnostic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('adresse', models.IntegerField(max_length=50)),
                ('dateNaiss', models.DateField()),
                ('specialite', models.CharField(max_length=20)),
                ('lieuTravail', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('adresse', models.IntegerField(max_length=50)),
                ('dateNaiss', models.DateField()),
                ('profession', models.CharField(max_length=20)),
                ('situationMatr', models.CharField(max_length=10)),
                ('assurance', models.CharField(max_length=10)),
                ('securiteSociale', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
