# Generated by Django 2.1.2 on 2018-11-11 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=15, verbose_name="Nature de l'antécédant")),
                ('description', models.CharField(max_length=30, verbose_name="Description de l'année")),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de consultation')),
                ('poids', models.FloatField(verbose_name='Poids')),
                ('temperature', models.FloatField(verbose_name='temperature')),
                ('tension', models.FloatField(verbose_name='Tension')),
                ('motifs', models.CharField(max_length=500, verbose_name='Motifs')),
                ('examenClinique', models.CharField(max_length=500, verbose_name='Examen Clinique')),
                ('diagnostic', models.CharField(max_length=100, verbose_name='Diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMaladie', models.TextField(verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ('nomMaladie',),
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('tel', models.IntegerField(verbose_name='Téléphone')),
                ('adresse', models.CharField(max_length=50, verbose_name='Adresse')),
                ('dateNaiss', models.DateField(verbose_name='Date de naissance')),
                ('specialite', models.CharField(max_length=20, verbose_name='Spécialité')),
                ('lieuTravail', models.CharField(max_length=20, verbose_name='Lieu de travail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('tel', models.IntegerField(verbose_name='Téléphone')),
                ('adresse', models.CharField(max_length=50, verbose_name='Adresse')),
                ('dateNaiss', models.DateField(verbose_name='Date de naissance')),
                ('profession', models.CharField(max_length=20, verbose_name='Profession')),
                ('situationMatr', models.CharField(max_length=10, verbose_name='Situation Matrimoniale')),
                ('assurance', models.CharField(max_length=10, verbose_name='Assurance')),
                ('securiteSociale', models.CharField(max_length=13, verbose_name='N° Sécurité sociale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSymptome', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ('nomSymptome',),
            },
        ),
        migrations.AddField(
            model_name='maladie',
            name='symptomes',
            field=models.ManyToManyField(to='dashboard.Symptome'),
        ),
    ]
