# Generated by Django 2.1.2 on 2018-10-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181019_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Antecedants',
            new_name='Antecedant',
        ),
    ]
