# Generated by Django 2.1.1 on 2018-10-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181019_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='securiteSociale',
            field=models.CharField(max_length=13),
        ),
    ]
