# Generated by Django 2.1.2 on 2019-01-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181229_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedant',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Patient'),
        ),
    ]
