# Generated by Django 2.1.2 on 2019-01-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_antecedant_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Medecin', verbose_name='Médecin'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='antecedant',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='temperature',
            field=models.FloatField(verbose_name='Température'),
        ),
    ]
