# Generated by Django 2.1.2 on 2018-10-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181019_1210'),
        ('dashboard', '0004_auto_20181019_1211'),
    ]

    operations = [
    ]
