# Generated by Django 2.1.2 on 2018-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_merge_20181022_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant',
            name='description',
            field=models.CharField(max_length=30, verbose_name="Description de l'année"),
        ),
        migrations.AlterField(
            model_name='antecedant',
            name='nature',
            field=models.CharField(max_length=15, verbose_name="Nature de l'antécédant"),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(verbose_name='Date de consultation'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnostic',
            field=models.CharField(max_length=100, verbose_name='Diagnostic'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='examenClinique',
            field=models.CharField(max_length=500, verbose_name='Examen Clinique'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motifs',
            field=models.CharField(max_length=500, verbose_name='Motifs'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='poids',
            field=models.FloatField(verbose_name='Poids'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='temperature',
            field=models.FloatField(verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='tension',
            field=models.FloatField(verbose_name='Tension'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='adresse',
            field=models.CharField(max_length=50, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='dateNaiss',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='lieuTravail',
            field=models.CharField(max_length=20, verbose_name='Lieu de travail'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='nom',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='prenom',
            field=models.CharField(max_length=30, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(max_length=20, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='tel',
            field=models.IntegerField(verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.CharField(max_length=50, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assurance',
            field=models.CharField(max_length=10, verbose_name='Assurance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateNaiss',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenom',
            field=models.CharField(max_length=30, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.CharField(max_length=20, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='securiteSociale',
            field=models.CharField(max_length=13, verbose_name='N° Sécurité sociale'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='situationMatr',
            field=models.CharField(max_length=10, verbose_name='Situation Matrimoniale'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel',
            field=models.IntegerField(verbose_name='Téléphone'),
        ),
    ]
