# Generated by Django 2.1.2 on 2019-01-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190103_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Patient', verbose_name='Patient'),
        ),
    ]
