# Generated by Django 2.1.2 on 2019-01-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190103_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant',
            name='description',
            field=models.CharField(max_length=30, verbose_name="Description de l'antécédent"),
        ),
        migrations.AlterField(
            model_name='antecedant',
            name='nature',
            field=models.CharField(max_length=15, verbose_name="Nature de l'antécédent"),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='tel',
            field=models.CharField(max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel',
            field=models.CharField(max_length=30, verbose_name='Téléphone'),
        ),
    ]
