# Generated by Django 2.1.2 on 2018-11-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20181022_1148'),
        ('dashboard', '0005_auto_20181107_1654'),
    ]

    operations = [
    ]
