# Generated by Django 2.1.2 on 2019-01-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190107_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='dateNaiss',
            field=models.CharField(max_length=15, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateNaiss',
            field=models.CharField(max_length=15, verbose_name='Date de naissance'),
        ),
    ]
