# Generated by Django 2.1.2 on 2018-11-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_merge_20181108_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSymptome', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('nomSymptome',),
            },
        ),
        migrations.AlterModelOptions(
            name='maladie',
            options={'ordering': ('nomMaladie',)},
        ),
        migrations.RemoveField(
            model_name='maladie',
            name='symptomes',
        ),
        migrations.AddField(
            model_name='maladie',
            name='symptomes',
            field=models.ManyToManyField(to='dashboard.Symptome'),
        ),
    ]
