# Generated by Django 2.1.2 on 2018-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20181108_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMaladie', models.CharField(max_length=50, unique=True)),
                ('listeSymptomes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='maladie',
            name='nomMaladie',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
