# Generated by Django 2.1.2 on 2019-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190107_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='situationMatr',
            field=models.CharField(choices=[('MARIE', 'Marié'), ('CELIBATAIRE', 'Célibataire')], max_length=50, verbose_name='Situation Matrimoniale'),
        ),
    ]
