# Generated by Django 2.1.2 on 2018-11-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20181108_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalData',
        ),
    ]
