# Generated by Django 2.1.2 on 2018-11-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMaladie', models.CharField(max_length=50, unique=True)),
                ('listeSymptomes', models.TextField(blank=True)),
            ],
        ),
    ]
