# Generated by Django 2.1.2 on 2018-11-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='nomMaladie',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
