# Generated by Django 2.1.2 on 2018-11-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181111_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldata',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
